// SITUACOES AGENDAMENTO COPIADO DO BACK-END
const ABERTO = 9;
const AGUARDANDO_CONFIRMACAO = 28;
const AGENDADO = 29;
const EM_ATENDIMENTO = 10;
const CANCELADO = 11;
const REMARCADO = 12;
const REALIZADO = 13;
const CONCLUIDO = 14;

const agendamento = {
	ABERTO,
	AGUARDANDO_CONFIRMACAO,
	AGENDADO,
	EM_ATENDIMENTO,
	CANCELADO,
	REMARCADO,
	REALIZADO,
	CONCLUIDO
}

export default agendamento;