// SITUACOES CONSULTORIA COPIADO DO BACK-END
const ABERTO = 30;
const AGENDADO = 31;
const EM_ANDAMENTO = 32;
const REALIZADO = 33;
const CONCLUIDO = 34;
const CANCELADO = 35;

const consultoria = {
	ABERTO,
	AGENDADO,
	EM_ANDAMENTO,
	REALIZADO,
	CONCLUIDO,
	CANCELADO
}

export default consultoria;